# Generated by Django 5.1.4 on 2024-12-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinecampaign',
            name='updated_at',
        ),
    ]
