# Generated by Django 5.1.4 on 2024-12-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_patient'),
        ('campaign', '0003_alter_vaccinecampaign_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinecampaign',
            name='doctor',
        ),
        migrations.AddField(
            model_name='vaccinecampaign',
            name='doctors',
            field=models.ManyToManyField(related_name='created_campaigns', to='accounts.doctor'),
        ),
    ]
