# Generated by Django 5.1.4 on 2024-12-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_patient'),
        ('campaign', '0004_remove_vaccinecampaign_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinecampaign',
            name='doctors',
        ),
        migrations.AddField(
            model_name='vaccinecampaign',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to='accounts.doctor'),
        ),
    ]
