# Generated by Django 5.1.4 on 2024-12-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_remove_vaccinecampaign_doctors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecampaign',
            name='dose_interval',
            field=models.PositiveIntegerField(default=28),
        ),
        migrations.AddField(
            model_name='vaccinecampaign',
            name='schedule',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
